#DAY 7

# NUMPY

In [7]:
import numpy as np

In [14]:
a=[3,4,5,6]
print(a)
print(type(a))


[3, 4, 5, 6]
<class 'list'>


AttributeError: 'list' object has no attribute 'dtype'

In [15]:
b=np.array(a)
print(b)
print(type(b))
print(b.dtype)

[3 4 5 6]
<class 'numpy.ndarray'>
int32


In [16]:
c=np.array([4,5,6,8.6,9])
print(c)
print(type(c))
print(c.dtype)

[4.  5.  6.  8.6 9. ]
<class 'numpy.ndarray'>
float64


In [196]:
d=np.array([4,5,6,8.6,6+7,9,'a','b'])
print(d)
print(type(d))
print(d.dtype)

['4' '5' '6' '8.6' '13' '9' 'a' 'b']
<class 'numpy.ndarray'>
<U32


In [21]:
numpy_array= np.array([5,6,8,10.22])
print("Array\n : ",numpy_array)
print("Array Type\n : ",type(numpy_array) )
print("Data type\n : ",numpy_array.dtype)
print("n Dimention\n : ",numpy_array.ndim)
print("Item size\n : ",numpy_array.itemsize)
#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving 
#the size of the array along each dimension.

print("Shape\n : ",numpy_array.shape)#in Rows,Columns
print("Nbytes\n : ",numpy_array.nbytes)



Array
 :  [ 5.    6.    8.   10.22]
Array Type
 :  <class 'numpy.ndarray'>
Data type
 :  float64
n Dimention
 :  1
Item size
 :  8
Shape
 :  (4,)
Nbytes
 :  32


In [202]:
# 2-D array

#d1=np.array([21,2,4,5,6,7])
#d2=np.array([[1,2,3],[4,5,6]])
#print(d1)
#print(d2)

a=np.array([[3,4,5],[6,7,8],[2,6,9]])

print(a)

print("Array\n : ",a)
print("Array Type\n : ",type(a) )
print("Data type\n : ",a.dtype)
print("n Dimention\n : ",a.ndim)
print("Item size\n : ",a.itemsize)
#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving 
#the size of the array along each dimension.

print("Shape\n : ",a.shape)#in Rows,Columns
print("Nbytes\n : ",a.nbytes)


[[3 4 5]
 [6 7 8]
 [2 6 9]]
Array
 :  [[3 4 5]
 [6 7 8]
 [2 6 9]]
Array Type
 :  <class 'numpy.ndarray'>
Data type
 :  int32
n Dimention
 :  2
Item size
 :  4
Shape
 :  (3, 3)
Nbytes
 :  36


In [28]:
#Type Conversion Int to Float
b=np.array([[3,4,5],[6,7,8]],dtype=float)
print(b)
print(b.dtype)

[[3. 4. 5.]
 [6. 7. 8.]]
float64


In [29]:
#Type Conversion FLOAT TO int
b=np.array([[3.3,4.4,5.5],[6.4,7.5,8.6]],dtype=int)
print(b)
print(b.dtype)

[[3 4 5]
 [6 7 8]]
int32


In [31]:
# a Matrix having all zero

z=np.zeros((4,7))
z


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
# a Matrix having all One

z=np.ones((4,7),dtype=int)
z


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [35]:
# For creating identity Matrix

e=np.eye((4))
e


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [207]:
full_array = np.full((4,8),190)
full_array

array([[190, 190, 190, 190, 190, 190, 190, 190],
       [190, 190, 190, 190, 190, 190, 190, 190],
       [190, 190, 190, 190, 190, 190, 190, 190],
       [190, 190, 190, 190, 190, 190, 190, 190]])

In [37]:
full_array = np.full((4,8),"G")
full_array

array([['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
       ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
       ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G'],
       ['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G']], dtype='<U1')

In [40]:
# Array with arange() function
a=np.arange(7)
print("Array with Range 7: \n",a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)





Array with Range 7: 
 [0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
1
(7,)


In [44]:
a=np.arange(2,7)
print("Array with Range : \n",a)

Array with Range : 
 [2 3 4 5 6]


In [45]:
a=np.arange(2,12,3)
print("Array with Range 7: \n",a)

Array with Range 7: 
 [ 2  5  8 11]


In [49]:
a=np.arange(3,28,3)
print("Array with Range : \n",a)

Array with Range : 
 [ 3  6  9 12 15 18 21 24 27]


In [64]:
# Generate Random nos.

randum=np.random.random((4,2))
randum


array([[0.89572636, 0.39080198],
       [0.30989927, 0.93010227],
       [0.94925128, 0.14068395],
       [0.18164213, 0.002937  ]])

In [213]:
# to generate integer random nos.

a=np.random.randint(1, 7, (3, 4))
a

array([[3, 6, 1, 2],
       [1, 2, 2, 1],
       [6, 2, 1, 3]])

In [65]:
# array Indexing
a=np.arange(2,13)
print(a)


[ 2  3  4  5  6  7  8  9 10 11 12]


In [66]:
a[4]

6

In [67]:
a[-2]

11

### Array Slicing

a[:]
a[start:]
a[:stop]
a[start:stop]
a[start:stop:step]


In [73]:
a[:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
a[3:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
a[:7]

array([2, 3, 4, 5, 6, 7, 8])

In [76]:
a[2:9]

array([ 4,  5,  6,  7,  8,  9, 10])

In [77]:
a[2:10:2]

array([ 4,  6,  8, 10])

In [81]:
a[::-2]

array([12, 10,  8,  6,  4,  2])

In [82]:
a[10:2:-2]

array([12, 10,  8,  6])

In [84]:
arr3=np.array([[1,2,3,4,5],[3,4,6,7,8],[4,7,9,2,3],[4,3,7,8,2],[7,3,4,5,2]])
print(arr3)

[[1 2 3 4 5]
 [3 4 6 7 8]
 [4 7 9 2 3]
 [4 3 7 8 2]
 [7 3 4 5 2]]


In [87]:
arr3[2][4]

3

In [86]:
arr3[3][2]

7

In [89]:
arr3[1][0]

3

In [90]:
arr3[-1][3]

5

In [91]:
arr3[-2][-3]

7

In [92]:
import numpy as np


In [93]:
arr3=np.array([[1,2,3,4,5],[3,4,6,7,8],[4,7,9,2,3],[4,3,7,8,2],[7,3,4,5,2]])
print(arr3)

[[1 2 3 4 5]
 [3 4 6 7 8]
 [4 7 9 2 3]
 [4 3 7 8 2]
 [7 3 4 5 2]]


# Slicing

#arr3[start row : stop row, start col: stop col]



In [225]:
arr3[2: ,3:]

array([[2, 3],
       [8, 2],
       [5, 2]])

In [104]:
arr3[:3,:4]

array([[1, 2, 3, 4],
       [3, 4, 6, 7],
       [4, 7, 9, 2]])

In [105]:
arr3[ : , : ]

array([[1, 2, 3, 4, 5],
       [3, 4, 6, 7, 8],
       [4, 7, 9, 2, 3],
       [4, 3, 7, 8, 2],
       [7, 3, 4, 5, 2]])

In [106]:
arr3[2:4,1:3]

array([[7, 9],
       [3, 7]])

In [107]:
arr3

array([[1, 2, 3, 4, 5],
       [3, 4, 6, 7, 8],
       [4, 7, 9, 2, 3],
       [4, 3, 7, 8, 2],
       [7, 3, 4, 5, 2]])

In [112]:
arr3[1:,2:]

array([[6, 7, 8],
       [9, 2, 3],
       [7, 8, 2],
       [4, 5, 2]])

In [118]:
#Reshaping of array

array=np.arange(1,13)
print("array Originally", array)
print(array.ndim)
print("\n")

array Originally [ 1  2  3  4  5  6  7  8  9 10 11 12]
1




In [229]:
#resh_array=array.reshape(4,3)
#resh_array=array.reshape(3,4)
resh_array=array.reshape(4,3)
print ("Reshaped : \n",resh_array)
print(resh_array.ndim)


Reshaped : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [123]:
#Resizing

a=np.array([[1,2,3],[4,5,6]])
print('\n',a)
print(a.shape)



 [[1 2 3]
 [4 5 6]]
(2, 3)


In [124]:
b=np.resize(a,(3,3))
print('\n',b)
print(b.shape)


 [[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)


In [126]:
c=np.resize(a,(3,4))
print('\n',c)
print(c.shape)


 [[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
(3, 4)


In [127]:
d=np.resize(a,(1,6))
print('\n',d)
print(d.shape)


 [[1 2 3 4 5 6]]
(1, 6)


In [ ]:
# Arthmetic operation in Array

a=np


In [128]:
a = np.arange(9).reshape(3,3)
print(a)
print(a.ndim)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [131]:
b= np.array([10,11,12])
print(b)
print(b.ndim)

[10 11 12]
1


In [133]:
c= np.array([[3,4,5],[6,7,8],[1,2,3]])
print(c)
print(c.ndim)

[[3 4 5]
 [6 7 8]
 [1 2 3]]
2


In [135]:
np.add(a,c)


array([[ 3,  5,  7],
       [ 9, 11, 13],
       [ 7,  9, 11]])

In [136]:
np.subtract(a,c)

array([[-3, -3, -3],
       [-3, -3, -3],
       [ 5,  5,  5]])

In [137]:
np.multiply(a,c)

array([[ 0,  4, 10],
       [18, 28, 40],
       [ 6, 14, 24]])

In [138]:
np.divide(a,c)

array([[0.        , 0.25      , 0.4       ],
       [0.5       , 0.57142857, 0.625     ],
       [6.        , 3.5       , 2.66666667]])

In [140]:
np.transpose(a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [141]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
b

array([10, 11, 12])

In [143]:
c

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3]])

In [144]:
np.add(a,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [145]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [147]:
d=np.array([[2,3],[1,2]])
d

array([[2, 3],
       [1, 2]])

In [149]:
np.add(a,d) # it means rows must be same

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [150]:
#Joining Array

a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [151]:
b=np.array([[5,6],[7,8],[9,4]])
print(b)

[[5 6]
 [7 8]
 [9 4]]


In [153]:

np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 4]])

In [154]:
c = np.array([[0,0],[1,1]])
print("Array 3 - \n" , c)
print('Joining 1, 2 & 3- \n' , np.concatenate((c,a,b)))


Array 3 - 
 [[0 0]
 [1 1]]
Joining 1, 2 & 3- 
 [[0 0]
 [1 1]
 [1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 4]]


In [159]:


print(a)
print("\n")
b=np.array([[5,6,7],[7,8,0]])
print(b)

np.concatenate((a,b))

[[1 2]
 [3 4]]


[[5 6 7]
 [7 8 0]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

# Axis0 = Row Wise ||  Axis1=Cols wise

In [158]:
print(a)
print("\n")
b=np.array([[5,6,7],[7,8,0]])
print(b)

np.concatenate((a,b),axis = 1)

[[1 2]
 [3 4]]


[[5 6 7]
 [7 8 0]]


array([[1, 2, 5, 6, 7],
       [3, 4, 7, 8, 0]])

In [ ]:
# Numpy with string

In [160]:
a=np.array(['ab'])
b=np.array(['cd'])

print(a.ndim)
print(b.ndim)
print(a)
print(b)

1
1
['ab']
['cd']


In [162]:
arr_1 = np.array((['abc', 'xyz'], ['hi','hello']))
print("\n Original Array 1 : \n" , arr_1)
print(arr_1.ndim)
arr_2 = np.array([['123'] , ['456']])
print("\n Original Array 2 : \n" , arr_2)
print(arr_2.ndim)


 Original Array 1 : 
 [['abc' 'xyz']
 ['hi' 'hello']]
2

 Original Array 2 : 
 [['123']
 ['456']]
2


In [231]:
np.char.add(arr_1,arr_2)

array([['abc123', 'xyz123'],
       ['hi456', 'hello456']], dtype='<U8')

In [165]:
a=np.array(['ab'])
b=np.array(['cd'])

print(a.ndim)
print(b.ndim)
print(a)
print(b)

np.char.add(a,b)

1
1
['ab']
['cd']


array(['abcd'], dtype='<U4')

In [166]:
# CAPITILIZING

a=np.array(['i am going to market'])
print(np.char.capitalize(a))

['I am going to market']


In [167]:
word = np.array([['MEN will be men', 'Imperial BLUE'], ['think different' , 'apple'], ['designed for drivng pleasure', 'BMW']])
print("\nOriginal Array : \n" , word)


word_cap = np.char.capitalize(word)
print("\nAfter .capitalize Array : \n" , word_cap)



Original Array : 
 [['MEN will be men' 'Imperial BLUE']
 ['think different' 'apple']
 ['designed for drivng pleasure' 'BMW']]

After .capitalize Array : 
 [['Men will be men' 'Imperial blue']
 ['Think different' 'Apple']
 ['Designed for drivng pleasure' 'Bmw']]


In [ ]:
# Converting LOWER CASE AND UPPERCASE

In [168]:
a=np.char.lower(['HeLLO','WORlD'])
print(a)

['hello' 'world']


In [169]:
a=np.char.upper(['HeLLO','WORlD'])
print(a)

['HELLO' 'WORLD']


In [171]:
#Splitting the String

s=np.char.split(["Hey there how are you?"])


In [177]:
s

array([list(['Hey', 'there', 'how', 'are', 'you?'])], dtype=object)

In [175]:
s[0][1]

'there'

In [178]:
s1=np.char.split(["Hey,there,how are you?"],sep=',')
print(s1)


[list(['Hey', 'there', 'how are you?'])]


In [179]:
# " Good morning $ to all $ the participants $ hope u are enjoying $ the session "
print(np.char.split(['Good morning OF to all OF the participants OF hope u are enjoying OF the session'], sep = 'OF'))


[list(['Good morning ', ' to all ', ' the participants ', ' hope u are enjoying ', ' the session'])]


In [183]:
#Strip

print(np.char.strip(['Well','When','HoW'],'W'))

['ell' 'hen' 'Ho']


In [189]:
print(np.char.strip(['WellWl','WWhen','HoW'],'W'))

['ellWl' 'hen' 'Ho']


In [190]:
print(np.char.strip(['WellWl','WWhen','HoW'],'W'))

['ellWl' 'hen' 'Ho']


In [191]:
print(np.char.strip(['asdsar','drain','rain'],'r'))

['asdsa' 'drain' 'ain']


In [192]:
string = np.array([['red', 'rome'], ['rain' , 'drain'], ['drape', 'bear']])
print("\nOriginal Array : \n" , string)


word_strip = np.char.strip(string, 'r')
print("\nAfter .strip Array : \n" , word_strip)



Original Array : 
 [['red' 'rome']
 ['rain' 'drain']
 ['drape' 'bear']]

After .strip Array : 
 [['ed' 'ome']
 ['ain' 'drain']
 ['drape' 'bea']]


In [193]:
sentence = np.array([['He wants to be a traveller.', 'He travels.'], ['He paints.' , 'He wants to be a painter.']])
print("\nOriginal Array : \n" , sentence)


replace_ = np.char.replace(sentence, 'wants to be', 'is a ')
print("\nAfter .replace Array : \n" , replace_)



Original Array : 
 [['He wants to be a traveller.' 'He travels.']
 ['He paints.' 'He wants to be a painter.']]

After .replace Array : 
 [['He is a  a traveller.' 'He travels.']
 ['He paints.' 'He is a  a painter.']]


In [3]:
import numpy as np

c=np.array([4,5,6,8,9])
print(c)


[4 5 6 8 9]


In [9]:
print (c[-3:])

[6 8 9]
